name: Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  push-to-docker-hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
        - name: Check out
          uses: actions/checkout@v6

        - name: Log in to Docker Hub
          uses: docker/login-action@v4
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v4

        - name: Build and push Docker image
          uses: docker/build-push-action@v7
          with:
            push: true
            tags: yngyu/flight-map:latest
            provenance: 'false'
